package com.redhat.insurance;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Car implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.String marca;

   private java.lang.String modelo;

   private java.lang.Integer riesgoAuto;

   public Car()
   {
   }

   public java.lang.String getMarca()
   {
      return this.marca;
   }

   public void setMarca(java.lang.String marca)
   {
      this.marca = marca;
   }

   public java.lang.String getModelo()
   {
      return this.modelo;
   }

   public void setModelo(java.lang.String modelo)
   {
      this.modelo = modelo;
   }

   public java.lang.Integer getRiesgoAuto()
   {
      return this.riesgoAuto;
   }

   public void setRiesgoAuto(java.lang.Integer riesgoAuto)
   {
      this.riesgoAuto = riesgoAuto;
   }

   public Car(java.lang.String marca, java.lang.String modelo,
         java.lang.Integer riesgoAuto)
   {
      this.marca = marca;
      this.modelo = modelo;
      this.riesgoAuto = riesgoAuto;
   }

}