package com.redhat.insurance;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Driver implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.Integer edad;

   private java.lang.String correo;

   private java.lang.String codigoPostal;

   private java.lang.String nombre;

   private java.lang.Integer riesgoConductor;

   public Driver()
   {
   }

   public java.lang.Integer getEdad()
   {
      return this.edad;
   }

   public void setEdad(java.lang.Integer edad)
   {
      this.edad = edad;
   }

   public java.lang.String getCorreo()
   {
      return this.correo;
   }

   public void setCorreo(java.lang.String correo)
   {
      this.correo = correo;
   }

   public java.lang.String getCodigoPostal()
   {
      return this.codigoPostal;
   }

   public void setCodigoPostal(java.lang.String codigoPostal)
   {
      this.codigoPostal = codigoPostal;
   }

   public java.lang.String getNombre()
   {
      return this.nombre;
   }

   public void setNombre(java.lang.String nombre)
   {
      this.nombre = nombre;
   }

   public java.lang.Integer getRiesgoConductor()
   {
      return this.riesgoConductor;
   }

   public void setRiesgoConductor(java.lang.Integer riesgoConductor)
   {
      this.riesgoConductor = riesgoConductor;
   }

   public Driver(java.lang.Integer edad, java.lang.String correo,
         java.lang.String codigoPostal, java.lang.String nombre,
         java.lang.Integer riesgoConductor)
   {
      this.edad = edad;
      this.correo = correo;
      this.codigoPostal = codigoPostal;
      this.nombre = nombre;
      this.riesgoConductor = riesgoConductor;
   }

}