package com.redhat.insurance;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Policy implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.Integer precio;

   private java.lang.String tipo;

   public Policy()
   {
   }

   public java.lang.Integer getPrecio()
   {
      return this.precio;
   }

   public void setPrecio(java.lang.Integer precio)
   {
      this.precio = precio;
   }

   public java.lang.String getTipo()
   {
      return this.tipo;
   }

   public void setTipo(java.lang.String tipo)
   {
      this.tipo = tipo;
   }

   public Policy(java.lang.Integer precio, java.lang.String tipo)
   {
      this.precio = precio;
      this.tipo = tipo;
   }

}